version: "3"
services:
  server:
    container_name: server
    image: keymetrics/pm2:latest-alpine
    user: node 
    working_dir: /server
    env_file: server-container.env
    networks:
      - chat-app-network
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - ./server:/server
    command: sh -c "npm install && pm2-runtime start ecosystem.config.js --env ${PM2_ENV_MODE}" 

networks:
  chat-app-network:
