version: "3"
services:

  redis:
    image: redis
    container_name: redis-service
    env_file: redis-container.env
    expose:
      - ${REDIS_PORT}
    networks:
      - chat-app-network

  server:
    container_name: server-service
    image: keymetrics/pm2:latest-alpine
    user: node 
    working_dir: /server
    env_file: server-container.env
    networks:
      - chat-app-network
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - ./server:/server
    command: sh -c "npm install && pm2-runtime start ecosystem.config.js --env ${PM2_ENV_MODE}"

networks:
  chat-app-network:
