version: "3.9"
services:
  # auth-service
  auth-service:
    container_name: auth-service
    image: node:16.13.2-alpine
    env_file: ./auth-service/.env
    working_dir: /auth-service
    user: node
    environment:
      -  PORT=${AUTH_SERVICE_PORT}
    ports:
      - ${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}
    volumes:
    - ./auth-service:/auth-service
    networks:
      - chat-app-network
    command: sh -c "npm run server:watch"
networks:
  chat-app-network:
