version: "3"
services:
  server:
    container_name: server
    image: keymetrics/pm2:latest-alpine
    user: node 
    working_dir: /server
    env_file: server.env
    networks:
      - chat-app-network
    ports:
      - "3000:3000"
    volumes:
      - ./server:/server
    command: "pm2-runtime start ecosystem.config.js --env production"

networks:
  chat-app-network:
