version: "3"
services:
  app:
    container_name: server
    image: node:10 
    user: node 
    working_dir: "/server"
    networks:
    - chat-app
    ports:
    - "3000:3000"
    volumes:
    - ./server:/server
    command: "node src/index.js"

networks:
  chat-app:
