version: "3.9"
services:
  # auth-service
  auth-service:
    container_name: ${COMPOSE_PROJECT_NAME}-auth-service
    image: node:16.13.2-alpine
    env_file: ./auth-service/.env
    working_dir: /auth-service
    user: node
    environment:
      -  PORT=${AUTH_SERVICE_PORT}
    ports:
      - ${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}
    volumes:
    - ./auth-service:/auth-service
    networks:
      - default
    command: sh -c "npm run server:install && npm run server:watch"
networks:
    default:
      name: ${COMPOSE_PROJECT_NAME}-network

