name: Auth Service Tests

on:
  push:
  pull_request:
    branches:    
      - master

jobs:

  tests:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: cd ./auth-service && npm run server:install
    - run: cd ./auth-service && npm run test
